### ISSUE TITLE
显示的字体可以加粗吗？

### ISSUE THREAD

**Issue by xfangfang** [Dawish/FlymeTabStrip#1]
如题所示，flyme6自带效果有字体加粗变化，但是通过设置 app:tabTextAppearance 不能使字体加粗，求解决办法。

**Comment by Dawish** [comment]
好像忘记加这个功能了

**Comment by Dawish** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
